In [9]:
import pandas as pd
import requests
import os

In [10]:
# Specify the path to the CSV file
file_path = r'D:\BIPLOV\Reference GeoData Preparation_Bundesland\BW\Flurstueck\Processing\Gemarkungen.csv'

# Read the CSV file into a DataFrame
df = pd.read_csv(file_path)

# Display the first few rows of the DataFrame to verify it's read correctly
df.head()

,fid,gml_id,gemarkung_id,gemarkung_name,gemeinde_id,gemeinde_name,kreis_id,kreis_name,regierungsbezirk_id,regierungsbezirk_name,beginn,ende
0,1,DEBWL001000001WA,5715,Munzingen,8311000,Freiburg im Breisgau,311,Freiburg,3,Freiburg,2024/01/01 00:00:00,NaN
1,2,DEBWL00100000278,6736,Holzschlag,8337022,Bonndorf im Schwarzwald,337,Waldshut,3,Freiburg,2024/01/01 00:00:00,NaN
2,3,DEBWL001000002ux,8791,Birkenhard,8426128,Warthausen,426,Biberach,4,Tübingen,2024/01/01 00:00:00,NaN
3,4,DEBWL001000002iw,7752,Auingen,8415053,Münsingen,415,Reutlingen,4,Tübingen,2024/01/01 00:00:00,NaN
4,5,DEBWL00100000104,676,Degmarn,8125078,Oedheim,125,Heilbronn,1,Stuttgart,2024/01/01 00:00:00,NaN

In [17]:
# Convert gemarkung_id to string and pad with zeros to ensure 4-digit length
df['gemarkung_id'] = df['gemarkung_id'].astype(str).str.zfill(4)

# Sort DataFrame by gemarkung_id in ascending order
df.sort_values(by='gemarkung_id', inplace=True)

# Export the modified DataFrame to 'Gemarkungen_modified.csv' without index
output_file = r'D:\BIPLOV\Reference GeoData Preparation_Bundesland\BW\Flurstueck\Processing\Gemarkungen_modified.csv'
df.to_csv(output_file, index=False, encoding='utf-8-sig')

# Display the modified DataFrame
df.head(100)

,fid,gml_id,gemarkung_id,gemarkung_name,gemeinde_id,gemeinde_name,kreis_id,kreis_name,regierungsbezirk_id,regierungsbezirk_name,beginn,ende,filename,full_filepath,download_url
2599,2600,DEBWL001000000Kn,0001,Freudenberg,8128039,Freudenberg,128,Main-Tauber-Kreis,1,Stuttgart,2024/01/01 00:00:00,NaN,ALKIS-oE_080001_Freudenberg_shp.zip,D:\BIPLOV\Reference GeoData Preparation_Bundes...,https://opengeodata.lgl-bw.de/data/alkis/ALKIS...
1898,1899,DEBWL001000000Kp,0002,Boxtal,8128039,Freudenberg,128,Main-Tauber-Kreis,1,Stuttgart,2024/01/01 00:00:00,NaN,ALKIS-oE_080002_Boxtal_shp.zip,D:\BIPLOV\Reference GeoData Preparation_Bundes...,https://opengeodata.lgl-bw.de/data/alkis/ALKIS...
2819,2820,DEBWL001000000Kr,0003,Ebenheid,8128039,Freudenberg,128,Main-Tauber-Kreis,1,Stuttgart,2024/01/01 00:00:00,NaN,ALKIS-oE_080003_Ebenheid_shp.zip,D:\BIPLOV\Reference GeoData Preparation_Bundes...,https://opengeodata.lgl-bw.de/data/alkis/ALKIS...
2417,2418,DEBWL001000000Kt,0004,Rauenberg,8128039,Freudenberg,128,Main-Tauber-Kreis,1,Stuttgart,2024/01/01 00:00:00,NaN,ALKIS-oE_080004_Rauenberg_shp.zip,D:\BIPLOV\Reference GeoData Preparation_Bundes...,https://opengeodata.lgl-bw.de/data/alkis/ALKIS...
384,385,DEBWL001000000Kv,0005,Wessental,8128039,Freudenberg,128,Main-Tauber-Kreis,1,Stuttgart,2024/01/01 00:00:00,NaN,ALKIS-oE_080005_Wessental_shp.zip,D:\BIPLOV\Reference GeoData Preparation_Bundes...,https://opengeodata.lgl-bw.de/data/alkis/ALKIS...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1310,1311,DEBWL001000000Nx,0152,Apfelbach,8128007,Bad Mergentheim,128,Main-Tauber-Kreis,1,Stuttgart,2024/01/01 00:00:00,NaN,ALKIS-oE_080152_Apfelbach_shp.zip,D:\BIPLOV\Reference GeoData Preparation_Bundes...,https://opengeodata.lgl-bw.de/data/alkis/ALKIS...
1313,1314,DEBWL001000000Nz,0153,Dainbach,8128007,Bad Mergentheim,128,Main-Tauber-Kreis,1,Stuttgart,2024/01/01 00:00:00,NaN,ALKIS-oE_080153_Dainbach_shp.zip,D:\BIPLOV\Reference GeoData Preparation_Bundes...,https://opengeodata.lgl-bw.de/data/alkis/ALKIS...
424,425,DEBWL001000000NB,0154,Edelfingen,8128007,Bad Mergentheim,128,Main-Tauber-Kreis,1,Stuttgart,2024/01/01 00:00:00,NaN,ALKIS-oE_080154_Edelfingen_shp.zip,D:\BIPLOV\Reference GeoData Preparation_Bundes...,https://opengeodata.lgl-bw.de/data/alkis/ALKIS...
1017,1018,DEBWL001000000ND,0155,Hachtel,8128007,Bad Mergentheim,128,Main-Tauber-Kreis,1,Stuttgart,2024/01/01 00:00:00,NaN,ALKIS-oE_080155_Hachtel_shp.zip,D:\BIPLOV\Reference GeoData Preparation_Bundes...,https://opengeodata.lgl-bw.de/data/alkis/ALKIS...
3207,3208,DEBWL001000000NF,0156,Herbsthausen,8128007,Bad Mergentheim,128,Main-Tauber-Kreis,1,Stuttgart,2024/01/01 00:00:00,NaN,ALKIS-oE_080156_Herbsthausen_shp.zip,D:\BIPLOV\Reference GeoData Preparation_Bundes...,https://opengeodata.lgl-bw.de/data/alkis/ALKIS...

In [19]:
# Generate the full URL for downloading
# df['download_url'] = 'https://opengeodata.lgl-bw.de/data/alkis/' + df['filename'].str.replace(' ', '_').str.replace('/', '_')
df['download_url'] = 'https://opengeodata.lgl-bw.de/data/alkis/' + df['filename']


# Function to download file
def download_file(url, save_path):
    with requests.get(url, stream=True) as r:
        r.raise_for_status()
        with open(save_path, 'wb') as f:
            for chunk in r.iter_content(chunk_size=8192):
                f.write(chunk)

# Directory to save downloaded files
download_dir = r'D:\BIPLOV\Reference GeoData Preparation_Bundesland\BW\Flurstueck\Processing\Downloads'

# Create the directory if it doesn't exist
os.makedirs(download_dir, exist_ok=True)

# Download each file
for index, row in df.iterrows():
    url = row['download_url']
    filename = row['filename']
    save_path = os.path.join(download_dir, filename)
    print(f"Downloading {filename}...")
    download_file(url, save_path)
    print(f"{filename} downloaded successfully.")

print("All files downloaded successfully.")

Downloading ALKIS-oE_080001_Freudenberg_shp.zip...
ALKIS-oE_080001_Freudenberg_shp.zip downloaded successfully.
Downloading ALKIS-oE_080002_Boxtal_shp.zip...
ALKIS-oE_080002_Boxtal_shp.zip downloaded successfully.
Downloading ALKIS-oE_080003_Ebenheid_shp.zip...
ALKIS-oE_080003_Ebenheid_shp.zip downloaded successfully.
Downloading ALKIS-oE_080004_Rauenberg_shp.zip...
ALKIS-oE_080004_Rauenberg_shp.zip downloaded successfully.
Downloading ALKIS-oE_080005_Wessental_shp.zip...
ALKIS-oE_080005_Wessental_shp.zip downloaded successfully.
Downloading ALKIS-oE_080010_Wertheim_shp.zip...
ALKIS-oE_080010_Wertheim_shp.zip downloaded successfully.
Downloading ALKIS-oE_080011_Bettingen_shp.zip...
ALKIS-oE_080011_Bettingen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080012_Dertingen_shp.zip...
ALKIS-oE_080012_Dertingen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080013_Dietenhan_shp.zip...
ALKIS-oE_080013_Dietenhan_shp.zip downloaded successfully.
Downloading ALKIS-oE_080014_Dörlesberg_shp.zip...
ALKIS-oE_080014_Dörlesberg_shp.zip downloaded successfully.
Downloading ALKIS-oE_080015_Grünenwört_shp.zip...
ALKIS-oE_080015_Grünenwört_shp.zip downloaded successfully.
Downloading ALKIS-oE_080016_Höhefeld_shp.zip...
ALKIS-oE_080016_Höhefeld_shp.zip downloaded successfully.
Downloading ALKIS-oE_080017_Kembach_shp.zip...
ALKIS-oE_080017_Kembach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080018_Lindelbach_shp.zip...
ALKIS-oE_080018_Lindelbach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080019_Mondfeld_shp.zip...
ALKIS-oE_080019_Mondfeld_shp.zip downloaded successfully.
Downloading ALKIS-oE_080020_Nassig_shp.zip...
ALKIS-oE_080020_Nassig_shp.zip downloaded successfully.
Downloading ALKIS-oE_080021_Reicholzheim_shp.zip...
ALKIS-oE_080021_Reicholzheim_shp.zip downloaded successfully.
Downloading ALKIS-oE_080022_Sachsenhausen_shp.zip...
ALKIS-oE_080022_Sachsenhausen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080023_Sonderriet_shp.zip...
ALKIS-oE_080023_Sonderriet_shp.zip downloaded successfully.
Downloading ALKIS-oE_080024_Urphar_shp.zip...
ALKIS-oE_080024_Urphar_shp.zip downloaded successfully.
Downloading ALKIS-oE_080025_Waldenhausen_shp.zip...
ALKIS-oE_080025_Waldenhausen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080030_Külsheim_shp.zip...
ALKIS-oE_080030_Külsheim_shp.zip downloaded successfully.
Downloading ALKIS-oE_080031_Eiersheim_shp.zip...
ALKIS-oE_080031_Eiersheim_shp.zip downloaded successfully.
Downloading ALKIS-oE_080032_Hundheim_shp.zip...
ALKIS-oE_080032_Hundheim_shp.zip downloaded successfully.
Downloading ALKIS-oE_080033_Steinbach_shp.zip...
ALKIS-oE_080033_Steinbach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080034_Steinfurt_shp.zip...
ALKIS-oE_080034_Steinfurt_shp.zip downloaded successfully.
Downloading ALKIS-oE_080035_Uissigheim_shp.zip...
ALKIS-oE_080035_Uissigheim_shp.zip downloaded successfully.
Downloading ALKIS-oE_080040_Werbach_shp.zip...
ALKIS-oE_080040_Werbach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080041_Brunntal_shp.zip...
ALKIS-oE_080041_Brunntal_shp.zip downloaded successfully.
Downloading ALKIS-oE_080042_Gamburg_shp.zip...
ALKIS-oE_080042_Gamburg_shp.zip downloaded successfully.
Downloading ALKIS-oE_080043_Niklashausen_shp.zip...
ALKIS-oE_080043_Niklashausen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080044_Wenkheim_shp.zip...
ALKIS-oE_080044_Wenkheim_shp.zip downloaded successfully.
Downloading ALKIS-oE_080045_Werbachhausen_shp.zip...
ALKIS-oE_080045_Werbachhausen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080050_Großrinderfeld_shp.zip...
ALKIS-oE_080050_Großrinderfeld_shp.zip downloaded successfully.
Downloading ALKIS-oE_080051_Gerchsheim_shp.zip...
ALKIS-oE_080051_Gerchsheim_shp.zip downloaded successfully.
Downloading ALKIS-oE_080052_Ilmspan_shp.zip...
ALKIS-oE_080052_Ilmspan_shp.zip downloaded successfully.
Downloading ALKIS-oE_080053_Schönfeld_shp.zip...
ALKIS-oE_080053_Schönfeld_shp.zip downloaded successfully.
Downloading ALKIS-oE_080060_Tauberbischofsheim_shp.zip...
ALKIS-oE_080060_Tauberbischofsheim_shp.zip downloaded successfully.
Downloading ALKIS-oE_080061_Dienstadt_shp.zip...
ALKIS-oE_080061_Dienstadt_shp.zip downloaded successfully.
Downloading ALKIS-oE_080062_Distelhausen_shp.zip...
ALKIS-oE_080062_Distelhausen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080063_Dittigheim_shp.zip...
ALKIS-oE_080063_Dittigheim_shp.zip downloaded successfully.
Downloading ALKIS-oE_080064_Dittwar_shp.zip...
ALKIS-oE_080064_Dittwar_shp.zip downloaded successfully.
Downloading ALKIS-oE_080065_Hochhausen_shp.zip...
ALKIS-oE_080065_Hochhausen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080066_Impfingen_shp.zip...
ALKIS-oE_080066_Impfingen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080070_Königheim_shp.zip...
ALKIS-oE_080070_Königheim_shp.zip downloaded successfully.
Downloading ALKIS-oE_080071_Brehmen_shp.zip...
ALKIS-oE_080071_Brehmen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080072_Gissigheim_shp.zip...
ALKIS-oE_080072_Gissigheim_shp.zip downloaded successfully.
Downloading ALKIS-oE_080073_Pülfringen_shp.zip...
ALKIS-oE_080073_Pülfringen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080075_Grünsfeld_shp.zip...
ALKIS-oE_080075_Grünsfeld_shp.zip downloaded successfully.
Downloading ALKIS-oE_080076_Grünsfeldhausen_shp.zip...
ALKIS-oE_080076_Grünsfeldhausen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080077_Krensheim_shp.zip...
ALKIS-oE_080077_Krensheim_shp.zip downloaded successfully.
Downloading ALKIS-oE_080078_Kützbrunn_shp.zip...
ALKIS-oE_080078_Kützbrunn_shp.zip downloaded successfully.
Downloading ALKIS-oE_080079_Paimar_shp.zip...
ALKIS-oE_080079_Paimar_shp.zip downloaded successfully.
Downloading ALKIS-oE_080080_Zimmern_shp.zip...
ALKIS-oE_080080_Zimmern_shp.zip downloaded successfully.
Downloading ALKIS-oE_080085_Oberwittighausen_shp.zip...
ALKIS-oE_080085_Oberwittighausen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080086_Poppenhausen_shp.zip...
ALKIS-oE_080086_Poppenhausen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080087_Unterwittighausen_shp.zip...
ALKIS-oE_080087_Unterwittighausen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080088_Vilchband_shp.zip...
ALKIS-oE_080088_Vilchband_shp.zip downloaded successfully.
Downloading ALKIS-oE_080090_Beckstein_shp.zip...
ALKIS-oE_080090_Beckstein_shp.zip downloaded successfully.
Downloading ALKIS-oE_080091_Deubach_shp.zip...
ALKIS-oE_080091_Deubach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080092_Gerlachsheim_shp.zip...
ALKIS-oE_080092_Gerlachsheim_shp.zip downloaded successfully.
Downloading ALKIS-oE_080093_Heckfeld_shp.zip...
ALKIS-oE_080093_Heckfeld_shp.zip downloaded successfully.
Downloading ALKIS-oE_080094_Königshofen_shp.zip...
ALKIS-oE_080094_Königshofen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080095_Lauda_shp.zip...
ALKIS-oE_080095_Lauda_shp.zip downloaded successfully.
Downloading ALKIS-oE_080096_Marbach_shp.zip...
ALKIS-oE_080096_Marbach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080097_Messelhausen_shp.zip...
ALKIS-oE_080097_Messelhausen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080098_Oberbalbach_shp.zip...
ALKIS-oE_080098_Oberbalbach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080099_Oberlauda_shp.zip...
ALKIS-oE_080099_Oberlauda_shp.zip downloaded successfully.
Downloading ALKIS-oE_080100_Sachsenflur_shp.zip...
ALKIS-oE_080100_Sachsenflur_shp.zip downloaded successfully.
Downloading ALKIS-oE_080101_Unterbalbach_shp.zip...
ALKIS-oE_080101_Unterbalbach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080110_Berolzheim_shp.zip...
ALKIS-oE_080110_Berolzheim_shp.zip downloaded successfully.
Downloading ALKIS-oE_080111_Buch_shp.zip...
ALKIS-oE_080111_Buch_shp.zip downloaded successfully.
Downloading ALKIS-oE_080112_Eubigheim_shp.zip...
ALKIS-oE_080112_Eubigheim_shp.zip downloaded successfully.
Downloading ALKIS-oE_080113_Hohenstadt_shp.zip...
ALKIS-oE_080113_Hohenstadt_shp.zip downloaded successfully.
Downloading ALKIS-oE_080114_Schillingstadt_shp.zip...
ALKIS-oE_080114_Schillingstadt_shp.zip downloaded successfully.
Downloading ALKIS-oE_080120_Boxberg_shp.zip...
ALKIS-oE_080120_Boxberg_shp.zip downloaded successfully.
Downloading ALKIS-oE_080121_Angeltürn_shp.zip...
ALKIS-oE_080121_Angeltürn_shp.zip downloaded successfully.
Downloading ALKIS-oE_080122_Bobstadt_shp.zip...
ALKIS-oE_080122_Bobstadt_shp.zip downloaded successfully.
Downloading ALKIS-oE_080123_Epplingen_shp.zip...
ALKIS-oE_080123_Epplingen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080124_Kupprichhausen_shp.zip...
ALKIS-oE_080124_Kupprichhausen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080125_Lengenrieden_shp.zip...
ALKIS-oE_080125_Lengenrieden_shp.zip downloaded successfully.
Downloading ALKIS-oE_080126_Oberschüpf_shp.zip...
ALKIS-oE_080126_Oberschüpf_shp.zip downloaded successfully.
Downloading ALKIS-oE_080127_Schwabhausen_shp.zip...
ALKIS-oE_080127_Schwabhausen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080128_Schweigern_shp.zip...
ALKIS-oE_080128_Schweigern_shp.zip downloaded successfully.
Downloading ALKIS-oE_080129_Uiffingen_shp.zip...
ALKIS-oE_080129_Uiffingen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080130_Unterschüpf_shp.zip...
ALKIS-oE_080130_Unterschüpf_shp.zip downloaded successfully.
Downloading ALKIS-oE_080131_Windischbuch_shp.zip...
ALKIS-oE_080131_Windischbuch_shp.zip downloaded successfully.
Downloading ALKIS-oE_080132_Wölchingen_shp.zip...
ALKIS-oE_080132_Wölchingen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080140_Igersheim_shp.zip...
ALKIS-oE_080140_Igersheim_shp.zip downloaded successfully.
Downloading ALKIS-oE_080141_Bernsfelden_shp.zip...
ALKIS-oE_080141_Bernsfelden_shp.zip downloaded successfully.
Downloading ALKIS-oE_080142_Harthausen_shp.zip...
ALKIS-oE_080142_Harthausen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080143_Neuses_shp.zip...
ALKIS-oE_080143_Neuses_shp.zip downloaded successfully.
Downloading ALKIS-oE_080144_Simmringen_shp.zip...
ALKIS-oE_080144_Simmringen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080150_Mergentheim_shp.zip...
ALKIS-oE_080150_Mergentheim_shp.zip downloaded successfully.
Downloading ALKIS-oE_080151_Althausen_shp.zip...
ALKIS-oE_080151_Althausen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080152_Apfelbach_shp.zip...
ALKIS-oE_080152_Apfelbach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080153_Dainbach_shp.zip...
ALKIS-oE_080153_Dainbach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080154_Edelfingen_shp.zip...
ALKIS-oE_080154_Edelfingen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080155_Hachtel_shp.zip...
ALKIS-oE_080155_Hachtel_shp.zip downloaded successfully.
Downloading ALKIS-oE_080156_Herbsthausen_shp.zip...
ALKIS-oE_080156_Herbsthausen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080157_Löffelstelzen_shp.zip...
ALKIS-oE_080157_Löffelstelzen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080158_Markelsheim_shp.zip...
ALKIS-oE_080158_Markelsheim_shp.zip downloaded successfully.
Downloading ALKIS-oE_080159_Neunkirchen_shp.zip...
ALKIS-oE_080159_Neunkirchen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080160_Rengershausen_shp.zip...
ALKIS-oE_080160_Rengershausen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080161_Rot_shp.zip...
ALKIS-oE_080161_Rot_shp.zip downloaded successfully.
Downloading ALKIS-oE_080162_Stuppach_shp.zip...
ALKIS-oE_080162_Stuppach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080163_Wachbach_shp.zip...
ALKIS-oE_080163_Wachbach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080170_Assamstadt_shp.zip...
ALKIS-oE_080170_Assamstadt_shp.zip downloaded successfully.
Downloading ALKIS-oE_080175_Weikersheim_shp.zip...
ALKIS-oE_080175_Weikersheim_shp.zip downloaded successfully.
Downloading ALKIS-oE_080176_Elpersheim_shp.zip...
ALKIS-oE_080176_Elpersheim_shp.zip downloaded successfully.
Downloading ALKIS-oE_080177_Haagen_shp.zip...
ALKIS-oE_080177_Haagen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080178_Honsbronn_shp.zip...
ALKIS-oE_080178_Honsbronn_shp.zip downloaded successfully.
Downloading ALKIS-oE_080179_Laudenbach_shp.zip...
ALKIS-oE_080179_Laudenbach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080180_Nassau_shp.zip...
ALKIS-oE_080180_Nassau_shp.zip downloaded successfully.
Downloading ALKIS-oE_080181_Neubronn_shp.zip...
ALKIS-oE_080181_Neubronn_shp.zip downloaded successfully.
Downloading ALKIS-oE_080182_Queckbronn_shp.zip...
ALKIS-oE_080182_Queckbronn_shp.zip downloaded successfully.
Downloading ALKIS-oE_080183_Schäftersheim_shp.zip...
ALKIS-oE_080183_Schäftersheim_shp.zip downloaded successfully.
Downloading ALKIS-oE_080190_Creglingen_shp.zip...
ALKIS-oE_080190_Creglingen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080191_Archshofen_shp.zip...
ALKIS-oE_080191_Archshofen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080192_Blumweiler_shp.zip...
ALKIS-oE_080192_Blumweiler_shp.zip downloaded successfully.
Downloading ALKIS-oE_080193_Craintal_shp.zip...
ALKIS-oE_080193_Craintal_shp.zip downloaded successfully.
Downloading ALKIS-oE_080194_Finsterlohr_shp.zip...
ALKIS-oE_080194_Finsterlohr_shp.zip downloaded successfully.
Downloading ALKIS-oE_080195_Frauental_shp.zip...
ALKIS-oE_080195_Frauental_shp.zip downloaded successfully.
Downloading ALKIS-oE_080196_Freudenbach_shp.zip...
ALKIS-oE_080196_Freudenbach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080197_Münster_shp.zip...
ALKIS-oE_080197_Münster_shp.zip downloaded successfully.
Downloading ALKIS-oE_080198_Niederrimbach_shp.zip...
ALKIS-oE_080198_Niederrimbach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080199_Oberrimbach_shp.zip...
ALKIS-oE_080199_Oberrimbach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080200_Reinsbronn_shp.zip...
ALKIS-oE_080200_Reinsbronn_shp.zip downloaded successfully.
Downloading ALKIS-oE_080201_Schmerbach_shp.zip...
ALKIS-oE_080201_Schmerbach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080202_Waldmannshofen_shp.zip...
ALKIS-oE_080202_Waldmannshofen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080205_Niederstetten_shp.zip...
ALKIS-oE_080205_Niederstetten_shp.zip downloaded successfully.
Downloading ALKIS-oE_080206_Adolzhausen_shp.zip...
ALKIS-oE_080206_Adolzhausen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080207_Herrenzimmern_shp.zip...
ALKIS-oE_080207_Herrenzimmern_shp.zip downloaded successfully.
Downloading ALKIS-oE_080208_Oberstetten_shp.zip...
ALKIS-oE_080208_Oberstetten_shp.zip downloaded successfully.
Downloading ALKIS-oE_080209_Pfitzingen_shp.zip...
ALKIS-oE_080209_Pfitzingen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080210_Rinderfeld_shp.zip...
ALKIS-oE_080210_Rinderfeld_shp.zip downloaded successfully.
Downloading ALKIS-oE_080211_Rüsselhausen_shp.zip...
ALKIS-oE_080211_Rüsselhausen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080212_Vorbachzimmern_shp.zip...
ALKIS-oE_080212_Vorbachzimmern_shp.zip downloaded successfully.
Downloading ALKIS-oE_080213_Wermutshausen_shp.zip...
ALKIS-oE_080213_Wermutshausen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080214_Wildentierbach_shp.zip...
ALKIS-oE_080214_Wildentierbach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080220_Krautheim_shp.zip...
ALKIS-oE_080220_Krautheim_shp.zip downloaded successfully.
Downloading ALKIS-oE_080221_Altkrautheim_shp.zip...
ALKIS-oE_080221_Altkrautheim_shp.zip downloaded successfully.
Downloading ALKIS-oE_080222_Gommersdorf_shp.zip...
ALKIS-oE_080222_Gommersdorf_shp.zip downloaded successfully.
Downloading ALKIS-oE_080223_Horrenbach_shp.zip...
ALKIS-oE_080223_Horrenbach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080224_Klepsau_shp.zip...
ALKIS-oE_080224_Klepsau_shp.zip downloaded successfully.
Downloading ALKIS-oE_080225_Neunstetten_shp.zip...
ALKIS-oE_080225_Neunstetten_shp.zip downloaded successfully.
Downloading ALKIS-oE_080226_Oberginsbach_shp.zip...
ALKIS-oE_080226_Oberginsbach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080227_Oberndorf_shp.zip...
ALKIS-oE_080227_Oberndorf_shp.zip downloaded successfully.
Downloading ALKIS-oE_080228_Unterginsbach_shp.zip...
ALKIS-oE_080228_Unterginsbach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080235_Dörzbach_shp.zip...
ALKIS-oE_080235_Dörzbach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080236_Hohebach_shp.zip...
ALKIS-oE_080236_Hohebach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080237_Laibach_shp.zip...
ALKIS-oE_080237_Laibach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080238_Meßbach_shp.zip...
ALKIS-oE_080238_Meßbach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080245_Mulfingen_shp.zip...
ALKIS-oE_080245_Mulfingen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080246_Ailringen_shp.zip...
ALKIS-oE_080246_Ailringen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080247_Buchenbach_shp.zip...
ALKIS-oE_080247_Buchenbach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080248_Eberbach_shp.zip...
ALKIS-oE_080248_Eberbach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080249_Hollenbach_shp.zip...
ALKIS-oE_080249_Hollenbach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080250_Jagstberg_shp.zip...
ALKIS-oE_080250_Jagstberg_shp.zip downloaded successfully.
Downloading ALKIS-oE_080251_Simprechtshausen_shp.zip...
ALKIS-oE_080251_Simprechtshausen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080252_Zaisenhausen_shp.zip...
ALKIS-oE_080252_Zaisenhausen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080255_Schöntal_shp.zip...
ALKIS-oE_080255_Schöntal_shp.zip downloaded successfully.
Downloading ALKIS-oE_080256_Aschhausen_shp.zip...
ALKIS-oE_080256_Aschhausen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080257_Berlichingen_shp.zip...
ALKIS-oE_080257_Berlichingen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080258_Bieringen_shp.zip...
ALKIS-oE_080258_Bieringen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080259_Marlach_shp.zip...
ALKIS-oE_080259_Marlach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080260_Oberkessach_shp.zip...
ALKIS-oE_080260_Oberkessach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080261_Sindeldorf_shp.zip...
ALKIS-oE_080261_Sindeldorf_shp.zip downloaded successfully.
Downloading ALKIS-oE_080262_Westernhausen_shp.zip...
ALKIS-oE_080262_Westernhausen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080263_Winzenhofen_shp.zip...
ALKIS-oE_080263_Winzenhofen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080270_Ingelfingen_shp.zip...
ALKIS-oE_080270_Ingelfingen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080271_Criesbach_shp.zip...
ALKIS-oE_080271_Criesbach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080272_Diebach_shp.zip...
ALKIS-oE_080272_Diebach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080273_Dörrenzimmern_shp.zip...
ALKIS-oE_080273_Dörrenzimmern_shp.zip downloaded successfully.
Downloading ALKIS-oE_080274_Eberstal_shp.zip...
ALKIS-oE_080274_Eberstal_shp.zip downloaded successfully.
Downloading ALKIS-oE_080275_Hermuthausen_shp.zip...
ALKIS-oE_080275_Hermuthausen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080276_Weldingsfelden_shp.zip...
ALKIS-oE_080276_Weldingsfelden_shp.zip downloaded successfully.
Downloading ALKIS-oE_080280_Künzelsau_shp.zip...
ALKIS-oE_080280_Künzelsau_shp.zip downloaded successfully.
Downloading ALKIS-oE_080281_Amrichshausen_shp.zip...
ALKIS-oE_080281_Amrichshausen_shp.zip downloaded successfully.
Downloading ALKIS-oE_080282_Belsenberg_shp.zip...
ALKIS-oE_080282_Belsenberg_shp.zip downloaded successfully.
Downloading ALKIS-oE_080283_Gaisbach_shp.zip...
ALKIS-oE_080283_Gaisbach_shp.zip downloaded successfully.
Downloading ALKIS-oE_080284_Kocherstetten_shp.zip...
ALKIS-oE_080284_Kocherstetten_shp.zip downloaded successfully.